apiVersion: v1
kind: ConfigMap
metadata:
  name: java-delegates
  namespace: default
data:
  DELEGATES: rust-clusterip.default.svc.cluster.local:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-pod
  template:
    metadata:
      labels:
        app: java-pod
    spec:
      containers:
      - name: java-container
        image: ratulb/grpc-java-debian
        imagePullPolicy: Always
        ports:
        - containerPort: 31031
        env:
        - name: DELEGATES
          valueFrom:
            configMapKeyRef:
              name: java-delegates
              key: DELEGATES
---
apiVersion: v1
kind: Service
metadata:
  name: java-clusterip
spec:
  selector:
    app: java-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 31031
